name: Motur application image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      name: Install required SW
        run: |
          sudo apt-get update
          sudo apt-get install git
    
      name: Build the Motur Docker image
      with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          run: ./build_rel_image.sh
