name: Motur application image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      name: Build the Motur Docker image
      with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          install:
              apt-get update -q -y
              apt-get install -q -y git
          run: ./build_rel_image.sh
